name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests
        run:  mvn -B test
# Build jobs
  build:
    # depends on test's job
    needs: tests
    name: Build
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      #Check-out your repository
      - uses: actions/checkout@v3
      #Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build the application using Maven
      - name: Build with Maven
        run: mvn -B package -DskipTests--file pom.xml
      - run: mkdir staging && cp target/*.jar staging
   